Repository ansible-ThoTeam/nexus3-oss, pull requests merged in 2019-10, with the labels that each got.

#202 Ongoing test for currently failing ci build
  requirements.txt
Labels: bug, maintenance

#204 Role name in documentation does not reflect real one.
  README.md
Labels: docfix

#199 Add check admin.password file exists
  tasks/nexus_install.yml
Labels: bug
