Repository ansible-ThoTeam/nexus3-oss, pull requests merged in 2020-01, with the labels that each got.

#219 Add cleanup policies management
  README.md
  defaults/main.yml
  files/groovy/create_cleanup_policies_from_list.groovy
  files/groovy/create_repos_from_list.groovy
  molecule/nexus_common_test_vars.yml
  tasks/main.yml
Labels: enhancement

#223 email set up by class instead of the interface
  files/groovy/setup_email.groovy
Labels: bug

#225 fixed ldap groovy
  files/groovy/setup_ldap.groovy
  pom.xml
Labels: bug, maintenance

#216 Add SYSVinit support
  handlers/main.yml
  tasks/main.yml
  tasks/nexus_install.yml
Labels: enhancement

#234 Fix for Python 3.x SELinux packages on RHEL/CentOS 8
  tasks/selinux-RedHat.yml
Labels: enhancement
